Hoodie_Shop/Controllers/ProductsController.cs
using First_Website.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Hoodie_Shop.Data;
using Hoodie_Shop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;

namespace Hoodie_Shop.Controllers
{
    public class ProductsController : Controller
    {
        public IActionResult Insert()
        {
            return View();
        }
        public IActionResult InsertConfirm(string name,int price,string color,int count, IFormFile titleImg, List<IFormFile>listOfImages, [FromServices] HoodieDb db)
        {
            Hoodie hoodie = new Hoodie();
            hoodie.name =name;
            hoodie.price =price;
            hoodie.color = color;
            hoodie.count =count;
            hoodie.isAvailable = true;
            byte[] titleImageBytes = new byte[titleImg.Length];
            titleImg.OpenReadStream().Read(titleImageBytes, 0, titleImageBytes.Length);
            hoodie.titleImage = titleImageBytes;
            MemoryStream TitleImgMemoryStream = new MemoryStream(titleImageBytes);
            Image imageForTitleImage = Image.FromStream(TitleImgMemoryStream);
            Bitmap bitmap = new Bitmap(imageForTitleImage,200,200*imageForTitleImage.Width / imageForTitleImage.Height);
            MemoryStream memoryStreamForTitleImg = new MemoryStream();
            bitmap.Save(memoryStreamForTitleImg, System.Drawing.Imaging.ImageFormat.Jpeg);
            hoodie.thumbNailTitleImg = memoryStreamForTitleImg.ToArray();
            hoodie.hoodieImgs = new List<HoodieImg>();
            listOfImages.ForEach(x =>
            {
                if (x != null)
                {
                    byte[] bytes = new byte[x.Length];
                    x.OpenReadStream().Read(bytes, 0, bytes.Length);
                    MemoryStream memoryStream = new MemoryStream(bytes);
                    Image image = Image.FromStream(memoryStream);
                    Bitmap bitmap = new Bitmap(image, 200, 200 * image.Width / image.Height);
                    MemoryStream memoryStream1 = new MemoryStream();
                    bitmap.Save(memoryStream1, System.Drawing.Imaging.ImageFormat.Jpeg);
                    HoodieImg hoodieImg = new HoodieImg()
                    {
                        img = bytes,
                        thumbNail = memoryStream1.ToArray()
                    };
                    hoodie.hoodieImgs.Add(hoodieImg);
                }
            });
            db.Add(hoodie);
            db.SaveChanges();
            //return Json("successful!!!");
            return RedirectToAction("index", "Admin");
        }
        public IActionResult Delete()
        {
            return View();
        }
        public IActionResult DeleteProducts(int id, [FromServices] HoodieDb db)
        {
            var product = db.hoodies.Find(id);
            if (product != null)
            {
                product.count = 0;
                db.SaveChanges();
                return RedirectToAction("index", "Admin");
            }
            else
            {
                return RedirectToAction("index", "Admin");
            }
        }
        public IActionResult SelectProducts([FromServices] HoodieDb db)
        {
            var products = db.hoodies.ToList();
            return Json(products);
        }
        public IActionResult ProductsCount([FromServices] HoodieDb db)
        {
            var count = db.hoodies.Count();
            return Json(count);
        }
    }
}

Hoodie_Shop/Views/Admin/Insert.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <title>Insert</title>
    <style>
        .error {
            color: red
        }
    </style>
</head>
<body>
    @model ProductViewModels
    <div class="container col-4 offset-4 ">
        <form id="insertFrm">
            <div class="form-group">
                <label>name</label>
                <input class="form-control" asp-for="name" />
            </div>
            <div class="form-group">
                <label>price</label>
                <input class="form-control" asp-for="price" />
            </div>
            <div class="form-group">
                <label>color</label>
                <input class="form-control" asp-for="color" />
            </div>
            <div class="custom-file">
                <input class="custom-file-input" asp-for="images" /> <label>انتخاب عکس</label>
            </div>
            <div class="custom-file">
                <input class="custom-file-input" asp-for="images" /> <label>انتخاب عکس</label>
            </div>
            <div class="custom-file">
                <input class="custom-file-input" asp-for="images" /> <label>انتخاب عکس</label>
            </div>
            <button id="btnAdd" type="submit" class="btn btn-primary">ثبت</button>
        </form>
    </div>
</body>
<script>
    $(function () {

        $(btnAdd).click(function () {
            $(insertFrm).validate({
                rules:
                {
                    name: "required",
                    price: "required",
                    color: "required",
                    images: "required"
                },
                messages:
                {
                    name: "enter a name",
                    price: "enter a price",
                    color: "enter a color",
                    images: "choose an image"
                },
                submitHandler: () =>
                {
                    let Name = $('#name').val()
                    let Price = $('#price').val()
                    let Color = $('#color').val()
                    let Imgs = $('#images').get(0).files
                    let form = new FormData()
                    form.append('name', Name)
                    form.append('price', Price)
                    form.append('color', Color)
                    for (var i = 0; i < Imgs.length; i++) {
                        form.append('images', Imgs[i])
                    }
                    $.ajax({
                        url: '/Admin/InsertConfirm',
                        type: 'post',
                        data: form,
                        datatype: 'json',
                        enctype: 'multipart/form-data',
                        contentType: false,
                        processData: false,
                        success: function (data) {
                            alert(data)
                            $(name).val(null)
                            $(price).val(null)
                            $(color).val(null)
                            $(images).val(null)
                        }

                    })
                }

            })

        })
    })
</script>
</html>

Hoodie_Shop/Views/Admin/index.cshtml
@using First_Website.Areas.Identity.Data;
@{
    ViewData["Title"] = "index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <style>
        .field-validation-error {
            color: red;
        }

        .error {
            color: red;
        }
    </style>
</head>
<body>
    <div class="container">

        <!--card area start-->
        <div class="container">
            <div class="row">
                <div class=" card col-sm-3 m-4">
                    <div class="card-header bg-primary">
                        <h1 id="h1UsersCount" class="text-center text-white"></h1>
                    </div>
                    <div class="card-body bg-white">
                        <h5 class="text-center">users</h5>
                    </div>
                </div>
                <div class="card col-sm-3 m-4">
                    <div class="card-header bg-primary">
                        <h1 id="h1ProductsCount" class="text-center text-white"></h1>
                    </div>
                    <div class="card-body bg-white">
                        <h5 class="text-center">products</h5>
                    </div>
                </div>
                <div class="card col-sm-3 m-4">
                    <div class="card-header bg-prima">
                        <h1 id="h1OrdersCount" class="text-center text-white"></h1>
                    </div>
                    <div class="card-body bg-white">
                        <h5 class="text-center">Orders</h5>
                    </div>
                </div>
            </div>
        </div>
        <!--card area end-->

    </div>
    <div class="container-fluid col">
        <div class="input-group">
            <h2 class="form-control text-white bg-primary text-center">Users</h2>
        </div>
        <!-- insert user form start-->
        @model RegisterViewModels
        <div class="customer-login-register">
            <h3 class="text-center mt-20">ثبت نام</h3>
            <div class="login-Register-info">
                <form asp-action="RegisterConfirm" asp-controller="Account">
                    <p class="coupon-input form-row-first">
                        <label>نام کاربری یا ایمیل </label>
                        <input asp-for="userName" type="text">
                        <span asp-validation-for="userName"></span>
                    </p>
                    <p class="coupon-input form-row-first">
                        <label> نام  </label>
                        <input asp-for="firstName" type="text">
                        <span asp-validation-for="firstName"></span>
                    </p>
                    <p class="coupon-input form-row-first">
                        <label>نام خانوادگی</label>
                        <input asp-for="lastName" type="text">
                        <span asp-validation-for="lastName"></span>
                    </p>
                    <p class="coupon-input form-row-last">
                        <label>رمز عبور</label>
                        <input type="password" asp-for="passWord">
                        <span asp-validation-for="passWord"></span>
                    </p>
                    <div class="clear"></div>
                    <p>
                        <input type="checkbox" asp-for="isAnAdmin" /><label>Register As Admin</label>
                    </p>
                    <button id="AddBtn" class="button-login" type="submit">ثبت نام</button>
                </form>
            </div>
        </div>
        <!-- insert user form end-->
        <!--Delete user start-->
        <div class="customer-login-register">
            <h3 class="text-center"> حذف</h3>
            <div class="login-Register-info">
                <form asp-controller="Account" asp-action="DeleteUsers">
                    <p class="coupon-input form-row-first">
                        <label>آیدی</label>
                        <input name="id" asp-for="DeleteId" type="text">
                        <span asp-validation-for="DeleteId"></span>
                    </p>
                    <div class="clear"></div>
                    <button id="delBtn" class="button-login" type="submit"> حذف</button>
                </form>
            </div>
        </div>
        <!--Delete user end-->
        <div class="container">
            <h3 class="text-center">جدول کاربر ها</h3>
            <table id="tblUser" class="table table-bordered mt-20">
                <tr>
                    <th>آیدی</th>
                    <th>نام کاربری</th>
                    <th>نام</th>
                    <th>نام خانوادگی</th>
                </tr>
                @foreach (var item in ViewData["usersList"] as List<ApplicationUser>)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.UserName</td>
                        <td>@item.firstName</td>
                        <td>@item.lastName</td>
                    </tr>
                }
            </table>
        </div>
    </div>
    <div class="container-fluid col">
        <div class="input-group">
            <h2 class="form-control text-white bg-primary text-center">Products</h2>
        </div>
    </div>
    <!--insert products start-->
    <div class="customer-login-register">
        <h3 class="text-center mt-20">افزودن کالا</h3>
        <div class="login-Register-info">
            <form id="insertform" asp-controller="Products" enctype="multipart/form-data" method="post" asp-action="InsertConfirm">
                <p class="coupon-input form-row-first">
                    <label>نام  </label>
                    <input name="name" asp-for="name" id="name"  type="text">
                    <span asp-validation-for="name"></span>
                </p>
                <p class="coupon-input form-row-first">
                    <label> قیمت  </label>
                    <input id="price" asp-for="price" name="price" type="text">
                    <span asp-validation-for="price"></span>
                </p>
                <p class="coupon-input form-row-first">
                    <label>رنگ</label>
                    <input id="color" name="color" asp-for="color" type="text">
                    <span asp-validation-for="color"></span>
                </p>
                <p class="coupon-input form-row-first">
                    <label>تعداد</label>
                    <input id="count" name="count" asp-for="count" type="text">
                    <span asp-validation-for="count"></span>
                </p> 
                <div class="custom-file">
                    <input type="file" name="titleImg" class="custom-file-input" asp-for="titleImage" /><label class="custom-file-label">انتخاب عکس اولیه</label>
                    <span asp-validation-for="titleImage"></span>
                </div>
                <div class="custom-file">
                    <input name="listOfImages" asp-for="images" class="custom-file-input" type="file"><label class="custom-file-label">انتخاب عکس</label>
                    <span asp-validation-for="images"></span>
                </div>
                <div class="custom-file">
                    <input name="listOfImages" asp-for="images" class="custom-file-input" type="file"><label class="custom-file-label">انتخاب عکس</label>
                    <span asp-validation-for="images"></span>
                </div>
                <div class="custom-file">
                    <input name="listOfImages" asp-for="images" class="custom-file-input" type="file"><label class="custom-file-label">انتخاب عکس</label>
                    <span asp-validation-for="images"></span>
                </div>
                <button id="AddProduct" class="button-login" type="submit"> افزودن</button>
            </form>
        </div>
    </div>
    <!--insert products end-->
    <!--Delete product start-->
    <div class="customer-login-register">
        <h3 class="text-center"> حذف</h3>
        <div class="login-Register-info">
            <form asp-controller="Products" asp-action="DeleteProducts">
                <p class="coupon-input form-row-first">
                    <label>آیدی</label>
                    <input name="id" asp-for="DeleteProductId" type="text">
                    <span asp-validation-for="DeleteProductId"></span>
                </p>
                <div class="clear"></div>
                <button id="delBtn" class="button-login" type="submit"> حذف</button>
            </form>
        </div>
    </div>
    <!--Delete product end-->
    <div class="container">
        <h3 class="text-center">جدول موجودی ها</h3>
        <table id="tblProduct" class="table table-bordered mt-20">
            <tr>
                <th>آیدی</th>
                <th>نام</th>
                <th>تعداد</th>
                <th>رنگ</th>
                <th>قیمت</th>
            </tr>
            @foreach (var product in ViewData["products"] as List<Hoodie>)
            {
                <tr>
                    <td>@product.id</td>
                    <td>@product.name</td>
                    <td>@product.count</td>
                    <td>@product.color</td>
                    <td>@product.price</td>
                </tr>
            }
        </table>
    </div>
      <div class="container">
        <h3 class="text-center">جدول ناموجودی ها</h3>
        <table id="tblProduct" class="table table-bordered mt-20">
            <tr>
                <th>آیدی</th>
                <th>نام</th>
                <th>تعداد</th>
                <th>رنگ</th>
                <th>قیمت</th>
            </tr>
            @foreach (var product in ViewData["notAvailable"] as List<Hoodie>)
            {
                <tr>
                    <td>@product.id</td>
                    <td>@product.name</td>
                    <td>@product.count</td>
                    <td>@product.color</td>
                    <td>@product.price</td>
                </tr>
            }
        </table>
    </div>
    <!--Admins table start-->
        <div class="container">
            <div class="input-group">
              <h3 class="form-control bg-primary text-white text-center">Admins</h3>
            </div>
            <div class="container">
              <table> </table>
            </div>
        </div>
    <!--Admins table end-->
    <!--Delete Admin start-->
    <div class="customer-login-register">
        <h3 class="text-center"> حذف</h3>
        <div class="login-Register-info">
            <form asp-controller="Account" asp-action="DeleteAdmins">
                <p class="coupon-input form-row-first">
                    <label>آیدی</label>
                    <input name="id" asp-for="DeleteProductId" type="text">
                    <span asp-validation-for="DeleteProductId"></span>
                </p>
                <div class="clear"></div>
                <button id="delBtn" class="button-login" type="submit"> حذف</button>
            </form>
        </div>
    </div>
    <!--Delete Admin end-->
</body>
<script>
    $(function () {

        $.get('Account/UsersCount', function (response) {
            $(h1UsersCount).append(response)
        })
        $.get('Products/ProductsCount', function (response) {
            $(h1ProductsCount).append(response)
        })
    })
</script>